var brand ="Mala-practica";
let counter = 100;
const token = "abcd123";

console.log(token);
counter = 199;
console.log(counter);

// comenterio de una linea 

/* este es un comentario
    multiline
*/

//interpolacion
let interpolation = `El valor de counter es: ${counter}`;
//Maneras de imprimir
console.log(interpolation);
console.log("El valor de counter es:", counter);
console.log("El valor de counter es"+counter);

const persons =[{
    "firstName": "Vail",
    "lastName": "Leon",
    "age": 40,
    "gender": "Male"
  }, {
    "firstName": "Arabella",
    "lastName": "Con",
    "age": 41,
    "gender": "Female"
  }, {
    "firstName": "Deeyn",
    "lastName": "Margeaux",
    "age": 59,
    "gender": "Female"
  }, {
    "firstName": "Deane",
    "lastName": "Hewet",
    "age": 17,
    "gender": "Male"
  }, {
    "firstName": "Lance",
    "lastName": "Arne",
    "age": 60,
    "gender": "Genderqueer"
  }, {
    "firstName": "Raimund",
    "lastName": "Desi",
    "age": 48,
    "gender": "Male"
  }, {
    "firstName": "Anne",
    "lastName": "Blondelle",
    "age": 44,
    "gender": "Female"
  }, {
    "firstName": "Edna",
    "lastName": "Mareah",
    "age": 73,
    "gender": "Female"
  }, {
    "firstName": "Taddeusz",
    "lastName": "Angel",
    "age": 25,
    "gender": "Male"
  }, {
    "firstName": "Louis",
    "lastName": "Sigismondo",
    "age": 53,
    "gender": "Male"
  }, {
    "firstName": "Tamara",
    "lastName": "Roshelle",
    "age": 23,
    "gender": "Female"
  }, {
    "firstName": "Lemmie",
    "lastName": "Rodolfo",
    "age": 49,
    "gender": "Male"
  }, {
    "firstName": "Willetta",
    "lastName": "Lula",
    "age": 56,
    "gender": "Female"
  }, {
    "firstName": "Sim",
    "lastName": "Bev",
    "age": 61,
    "gender": "Male"
  }, {
    "firstName": "Padraic",
    "lastName": "Stuart",
    "age": 74,
    "gender": "Male"
  }, {
    "firstName": "Liane",
    "lastName": "Jocelyne",
    "age": 17,
    "gender": "Female"
  }, {
    "firstName": "Linoel",
    "lastName": "Blondell",
    "age": 29,
    "gender": "Polygender"
  }, {
    "firstName": "Milicent",
    "lastName": "Emilia",
    "age": 82,
    "gender": "Female"
  }, {
    "firstName": "Fonzie",
    "lastName": "Bradly",
    "age": 51,
    "gender": "Male"
  }, {
    "firstName": "Abbie",
    "lastName": "Damiano",
    "age": 49,
    "gender": "Male"
  }, {
    "firstName": "Mabelle",
    "lastName": "Conway",
    "age": 55,
    "gender": "Genderfluid"
  }, {
    "firstName": "Jacquetta",
    "lastName": "Kai",
    "age": 71,
    "gender": "Female"
  }, {
    "firstName": "Augusto",
    "lastName": "Nikolaus",
    "age": 73,
    "gender": "Male"
  }, {
    "firstName": "Joaquin",
    "lastName": "Moira",
    "age": 95,
    "gender": "Agender"
  }, {
    "firstName": "Arabella",
    "lastName": "Alyce",
    "age": 53,
    "gender": "Female"
  }, {
    "firstName": "Romy",
    "lastName": "Delcina",
    "age": 23,
    "gender": "Polygender"
  }, {
    "firstName": "Kellen",
    "lastName": "Madonna",
    "age": 92,
    "gender": "Female"
  }, {
    "firstName": "Cal",
    "lastName": "Berry",
    "age": 32,
    "gender": "Female"
  }, {
    "firstName": "Wenona",
    "lastName": "Valina",
    "age": 70,
    "gender": "Female"
  }, {
    "firstName": "Towny",
    "lastName": "Doe",
    "age": 100,
    "gender": "Polygender"
  }, {
    "firstName": "Braden",
    "lastName": "Bryna",
    "age": 80,
    "gender": "Genderfluid"
  }, {
    "firstName": "Barthel",
    "lastName": "Broderic",
    "age": 94,
    "gender": "Male"
  }, {
    "firstName": "Caroljean",
    "lastName": "Harmonia",
    "age": 88,
    "gender": "Female"
  }, {
    "firstName": "Chance",
    "lastName": "Cornell",
    "age": 72,
    "gender": "Male"
  }, {
    "firstName": "Bengt",
    "lastName": "Alistair",
    "age": 53,
    "gender": "Male"
  }, {
    "firstName": "Aileen",
    "lastName": "Mallory",
    "age": 30,
    "gender": "Female"
  }, {
    "firstName": "Zollie",
    "lastName": "Derril",
    "age": 82,
    "gender": "Male"
  }, {
    "firstName": "Cristal",
    "lastName": "Caryn",
    "age": 22,
    "gender": "Female"
  }, {
    "firstName": "Vikki",
    "lastName": "Verla",
    "age": 71,
    "gender": "Female"
  }, {
    "firstName": "Kendricks",
    "lastName": "Rossy",
    "age": 41,
    "gender": "Male"
  }, {
    "firstName": "Jerrome",
    "lastName": "Perice",
    "age": 15,
    "gender": "Male"
  }, {
    "firstName": "Brandy",
    "lastName": "Bruno",
    "age": 18,
    "gender": "Male"
  }, {
    "firstName": "Syd",
    "lastName": "Carr",
    "age": 66,
    "gender": "Male"
  }, {
    "firstName": "Rickie",
    "lastName": "Wayland",
    "age": 24,
    "gender": "Male"
  }, {
    "firstName": "Finn",
    "lastName": "Kerr",
    "age": 36,
    "gender": "Male"
  }, {
    "firstName": "Barry",
    "lastName": "Jewell",
    "age": 7,
    "gender": "Female"
  }, {
    "firstName": "Moreen",
    "lastName": "Eleanora",
    "age": 1,
    "gender": "Female"
  }, {
    "firstName": "Thorin",
    "lastName": "Nat",
    "age": 22,
    "gender": "Male"
  }, {
    "firstName": "Carree",
    "lastName": "Cecilia",
    "age": 98,
    "gender": "Female"
  }, {
    "firstName": "Sanford",
    "lastName": "Terrell",
    "age": 83,
    "gender": "Male"
  }, {
    "firstName": "Dyane",
    "lastName": "Leoline",
    "age": 43,
    "gender": "Female"
  }, {
    "firstName": "Marshall",
    "lastName": "Jacobo",
    "age": 11,
    "gender": "Male"
  }, {
    "firstName": "Noelani",
    "lastName": "Thelma",
    "age": 65,
    "gender": "Female"
  }, {
    "firstName": "Talbert",
    "lastName": "Javier",
    "age": 74,
    "gender": "Male"
  }, {
    "firstName": "Wylie",
    "lastName": "Rodolphe",
    "age": 1,
    "gender": "Male"
  }, {
    "firstName": "Ram",
    "lastName": "Constantin",
    "age": 86,
    "gender": "Male"
  }, {
    "firstName": "Jacintha",
    "lastName": "Ted",
    "age": 99,
    "gender": "Female"
  }, {
    "firstName": "Harris",
    "lastName": "Clyve",
    "age": 97,
    "gender": "Male"
  }, {
    "firstName": "Loni",
    "lastName": "Dreddy",
    "age": 65,
    "gender": "Female"
  }, {
    "firstName": "Baudoin",
    "lastName": "Gaile",
    "age": 36,
    "gender": "Male"
  }, {
    "firstName": "Jorry",
    "lastName": "Devi",
    "age": 89,
    "gender": "Female"
  }, {
    "firstName": "Kendall",
    "lastName": "Vinny",
    "age": 95,
    "gender": "Male"
  }, {
    "firstName": "Bernita",
    "lastName": "Lenee",
    "age": 60,
    "gender": "Female"
  }, {
    "firstName": "Asher",
    "lastName": "Boone",
    "age": 48,
    "gender": "Male"
  }, {
    "firstName": "Dorry",
    "lastName": "Tamiko",
    "age": 62,
    "gender": "Female"
  }, {
    "firstName": "Sallyanne",
    "lastName": "Pauly",
    "age": 60,
    "gender": "Female"
  }, {
    "firstName": "Jordon",
    "lastName": "Pall",
    "age": 17,
    "gender": "Male"
  }, {
    "firstName": "Herold",
    "lastName": "Raleigh",
    "age": 83,
    "gender": "Male"
  }, {
    "firstName": "Codi",
    "lastName": "Heriberto",
    "age": 86,
    "gender": "Male"
  }, {
    "firstName": "Kenyon",
    "lastName": "Isidro",
    "age": 78,
    "gender": "Male"
  }, {
    "firstName": "Yorgo",
    "lastName": "Vaughan",
    "age": 59,
    "gender": "Male"
  }, {
    "firstName": "Dayna",
    "lastName": "Marian",
    "age": 5,
    "gender": "Female"
  }, {
    "firstName": "Ernst",
    "lastName": "Dagny",
    "age": 19,
    "gender": "Male"
  }, {
    "firstName": "Cody",
    "lastName": "Etan",
    "age": 59,
    "gender": "Male"
  }, {
    "firstName": "Amargo",
    "lastName": "Celestina",
    "age": 23,
    "gender": "Female"
  }, {
    "firstName": "Vyky",
    "lastName": "Beitris",
    "age": 48,
    "gender": "Female"
  }, {
    "firstName": "Marnie",
    "lastName": "Margot",
    "age": 52,
    "gender": "Female"
  }, {
    "firstName": "Cordey",
    "lastName": "Ermengarde",
    "age": 13,
    "gender": "Female"
  }, {
    "firstName": "Kittie",
    "lastName": "Gennie",
    "age": 24,
    "gender": "Female"
  }, {
    "firstName": "Bryna",
    "lastName": "Darline",
    "age": 34,
    "gender": "Bigender"
  }, {
    "firstName": "Derrick",
    "lastName": "Judon",
    "age": 31,
    "gender": "Male"
  }, {
    "firstName": "Berty",
    "lastName": "Gannie",
    "age": 23,
    "gender": "Male"
  }, {
    "firstName": "Rachael",
    "lastName": "Kandy",
    "age": 71,
    "gender": "Female"
  }, {
    "firstName": "Delmore",
    "lastName": "Hymie",
    "age": 16,
    "gender": "Male"
  }, {
    "firstName": "Minetta",
    "lastName": "Amberly",
    "age": 52,
    "gender": "Agender"
  }, {
    "firstName": "Flossi",
    "lastName": "Genna",
    "age": 74,
    "gender": "Female"
  }, {
    "firstName": "Collette",
    "lastName": "Vitoria",
    "age": 72,
    "gender": "Female"
  }, {
    "firstName": "Amalita",
    "lastName": "Denna",
    "age": 31,
    "gender": "Female"
  }, {
    "firstName": "Ashlin",
    "lastName": "Adolphus",
    "age": 56,
    "gender": "Male"
  }, {
    "firstName": "Palm",
    "lastName": "Marwin",
    "age": 44,
    "gender": "Male"
  }, {
    "firstName": "Pierre",
    "lastName": "Rodolphe",
    "age": 36,
    "gender": "Male"
  }, {
    "firstName": "Leigh",
    "lastName": "Blane",
    "age": 57,
    "gender": "Genderfluid"
  }, {
    "firstName": "Sela",
    "lastName": "Whitaker",
    "age": 85,
    "gender": "Non-binary"
  }, {
    "firstName": "Robenia",
    "lastName": "Gratia",
    "age": 49,
    "gender": "Female"
  }, {
    "firstName": "Carter",
    "lastName": "Cesaro",
    "age": 90,
    "gender": "Male"
  }, {
    "firstName": "Trefor",
    "lastName": "Tulley",
    "age": 79,
    "gender": "Male"
  }, {
    "firstName": "Simonette",
    "lastName": "Maggie",
    "age": 82,
    "gender": "Female"
  }, {
    "firstName": "Fionnula",
    "lastName": "Fawn",
    "age": 93,
    "gender": "Female"
  }, {
    "firstName": "Sherrie",
    "lastName": "Christiane",
    "age": 92,
    "gender": "Female"
  }, {
    "firstName": "Weylin",
    "lastName": "Rudy",
    "age": 57,
    "gender": "Male"
  }];

console.table(persons);